### ISSUE TITLE
ID card login using separate domain

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#100]
Can we implement ID card authentication for rwapi using separate domain to overcome nginx limitation (https://www.id.ee/public/ID-kaardiga_autentimine_NGINX_serveril.pdf)?

**Comment by enmust** [comment]
I believe this is correct and updated link: https://www.id.ee/public/1902_-_Ubuntu_NGINX_veebiserveri_SSL_haalestus.pdf
