### ISSUE TITLE
keyword fields issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#103]
Add the field "author_keywords" after abstract, as regular text field, so that user can copy-paste keywords from a publication.

Convert the current Keywords field (=tags) to regular text control. Eventually this field will probably not be needed.

reference_keyword entries linked to reference should be addable/removable using the multi-select control (as currently used for tags). The option values would come from the keyword table (https://rwapi.geocollections.info/keyword/) and should be linked to the reference using the reference_keyword table (which could actually become Django many-to-many field).
A similar keyword component would later be added to attachment, to replace the current solution there.

**Comment by enmust** [comment]
Added said functionality to reference but this multi-select field is currently disabled because it needs API support.

**Comment by ollehints** [comment]
enabled the control for testing, but cannot find the problem with API. 
Regarding functionality, if a required keyword is not present in the keyword table, then the user should be able to add it via the same control (into the keyword table, and then also to reference_keyword).

**Comment by ollehints** [comment]
was mysql problem, existing keywords can now be added.

**Comment by ollehints** [comment]
when opening a reference, existing keywords are not shown. if user select new keywords, old ones will be deleted.

**Comment by enmust** [comment]
Should work now
