### ISSUE TITLE
Implement DOI management and registration

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#104]
Implement DOI data management and registration at DataCite server, based on working php application.
First the metadata should be saved in local system. Form for this should be based on the present file add/edit views. In most cases DOI will be linked to file(s) in the database so it should be easy to jump from file management to DOI view, auto filling many fields. First need to get API working for doi and sub-objects.

The registration requires communication with DataCite server using REST API and json data (the current php version uses xml). Full technical specification is available at: https://support.datacite.org/docs/mds-api-guide and https://support.datacite.org/docs/api and https://support.datacite.org/reference/dois-2

The current data entry/edit form looks like this:
![image](https://user-images.githubusercontent.com/14974887/53081209-06658000-3503-11e9-9039-b21b25b387d6.png)

**Comment by enmust** [comment]
DataCite checking is implemented in API
