### ISSUE TITLE
front page info

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#111]
On front page, user should see recent activities: 10 last added and 10 last changed records, based on data in Logs. The list should include links to particular records.

**Comment by enmust** [comment]
Added 10 latest user added and changed records but should there also be a way to see global added and changed records. For example I could make a radio button which switches between user and global mode

**Comment by enmust** [comment]
Also I can't order by time (descending) because it throws error.

**Comment by ollehints** [comment]
global statistics will come some time in the future to replace the current php functions. here it is to fill space and get user to the recent records by one click. 
-id will provide the desired order in most cases.

**Comment by enmust** [comment]
Closing this now because current desired functionality is delivered
