### ISSUE TITLE
ask user before leaving changed record

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#121]
If user changed a record and tries to leave without saving, a popup should ask "Are you sure you wand to leave without saving the edits?" / "Kas olete kindel, et soovite lahkuda ilma muudatusi salvestamata", with buttons "Yes, leave" / "Continue editing" / "Save the record".

**Comment by ollehints** [comment]
The desired behaviour is that if user, after changing some data, clicks header menu or otherwise tries to leave the active record / page, the popup will be shown. However, on red button click, it may be assumed that the user conciously decided to leave the page without saving and the popup is not necessary.

**Comment by enmust** [comment]
Ok, I'll make the changes tomorrow
