### ISSUE TITLE
number formatting and save function

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#129]
Sample form will save the record even if nothing has changed, since number formats between server and client are different:
`{'longitude1': {'new': 12, 'old': 12.0}, 'latitude1': {'new': 213, 'old': 213.0}}`

**Comment by OlesjaSenkiv** [comment]
The problem does not exist any more
![image](https://user-images.githubusercontent.com/25752623/54986186-dd7d5280-4fba-11e9-9167-e9361cb2b7cd.png)
