### ISSUE TITLE
subform edit row

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#131]
Existing subform rows, such as in locality_reference form, should become editable. Every row should have E and D buttons on the right. The default new record add row should also have both S and X buttons on the row, not below the table. If an existing row becomes editable the buttons would turn S and X. The D button will do nothing at the moment, waiting delete to be implemented in API.

**Comment by OlesjaSenkiv** [comment]
Edit functionality implemented for locality and sample related data
