### ISSUE TITLE
sample add link to existing attachment

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#133]
If adding an existing file to a sample, then multiple records will be shown in the table if the file has more than one relation: https://edit2.geocollections.info/sample/144987.

attachment search should match also attachment ID in addition to filename.

**Comment by OlesjaSenkiv** [comment]
The problem does not exist any more
![image](https://user-images.githubusercontent.com/25752623/54986413-44027080-4fbb-11e9-82b7-6e32a121e744.png)
