### ISSUE TITLE
save as new issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#136]
save as new function saves more records than expected skipping some fields. Saving one copy of sample 145000 resulted in creation of 12 uneccessary records, which are not duplicates of 145000. One "save as new" click resulted in following requests: 
![image](https://user-images.githubusercontent.com/14974887/54754376-0634cf00-4bec-11e9-9c28-be7b473366c2.png)

**Comment by OlesjaSenkiv** [comment]
I couldn't reproduce adding of multiple records. Maybe some old code... but in any way keep bug record so that i could investigate the problem.
