### ISSUE TITLE
sample analyses subform edit issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#141]
Few things:
- table not showing methods unless in row editing mode
- date selection is one day off from what is saved and what is selected
- is_private tickmark not functioning
- Select Date label should be smaller, as other data and labels
- Multiselect data / label should also be smaller
- Multiselect field should not have the lengthy "Press enter to select" message as on smaller screens  the data will not be visible
- Button icons/colors would work like this: 
  - there will be green pencil and red x buttons on all rows; no buttons with letters are neccessary
  - new row should have filled green button which saves the record, and filled red x button which empties the row and cancels the add operation
  - on existing rows there will be green border button and red border button; clicking on green activates row editing, and the button becomes filled green to act as save button; on save the data will be refreshed and initial state is back; the red button requires two clicks to delete the row, on first click the button turns filled red.
- reload the tab data after save
- add read-only analysis ID field
- calendar icons are off the field and grid:
![image](https://user-images.githubusercontent.com/14974887/54864566-aeb86f80-4d61-11e9-9f88-baff11d5f5a6.png)

**Comment by OlesjaSenkiv** [comment]
> date selection is one day off from what is saved and what is selected
This problem is occurred everywhere where the following logic is used typeof date === 'string' ? date.split('T')[0] : localISOTime.split('T')[0];}, (failide laadimisel jne). 
Solution is to use formatDateForUpload function.
