### ISSUE TITLE
digitised reference on save behavior

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#144]
When [save] new digitised reference, user should be taken to the list view; when [Save and add another] is clicked, then the previous filename should be cleared. Also, the reference combo should be cleared as every reference may have just one directly linked pdf - so there is no point saving the reference as default in this case.

**Comment by enmust** [comment]
At the moment line which creates relation with locality gives error, that's why redirect is not working.

**Comment by enmust** [comment]
@OlesjaSenkiv 
![image](https://user-images.githubusercontent.com/14908993/55096692-06890a80-50c3-11e9-9816-550376b46e92.png)
this line in that function
![image](https://user-images.githubusercontent.com/14908993/55096723-199bda80-50c3-11e9-8a1a-618c9b77b0bb.png)
