### ISSUE TITLE
trim reference data fields before sending to API

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#145]
Reference form is commonly filled via copy-paste. Too often users copy also invisible trailing whitespace characters and then the list view becomes ugly - space appears before dot or comma. Can we trim trailing whitespaces before sending data to API?

**Comment by ollehints** [comment]
example output:
`Donovan, S. K. & Hensley, C. , 2006. Gastrochaenolites Leymerie in the Cenozoic of the Antillean region . Ichnos 13, 1, 11-19.`

**Comment by enmust** [comment]
Am I right that whitespace should be removed:

- at the start and end of the string
- before dot or comma
- more than two whitespace should be replaced with one whitespace

or should there be more rules

**Comment by ollehints** [comment]
just remove all whitespaces from the start and end. not from within.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
