### ISSUE TITLE
add pdf to reference

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#146]
Adding pdf to reference is not convenient at the moment and requires switching between reference and attachment views. Can we add drag-and-drop file field for for uploading pdf directly from the reference form? The attachment object to be created would get reference_id from current reference, user_added=current_user, date added=now and is_private=1 (unless the reference is open access (is_oa=1). Later user can check/change the data in attachment view.

**Comment by enmust** [comment]
and user should be able to add only 1 file?

**Comment by ollehints** [comment]
yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ollehints** [comment]
Better to use pdf function only for existing references so that we can avoid related data usage and POST directly to /add/attachment.
