### ISSUE TITLE
Library issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#157]
- References list view should be on separate tab, and the editable tabular form would be on the other tab - there is no need to display them at the same time.
- Tabular form accepts new data but existing data cannot be edited - api tells reference__reference cannot be edited.
- Tabular form should have page size option selectable by user, or set a smaller number by default.
- We need html text widget with minimal formatting options (bold, italic, link) for abstract field.  
- In the future we need a more user friendly way for sorting records.

**Comment by enmust** [comment]
Added text editor widget with bold, italic and link options.
Also other editing options can be added in the future. [Link to widget](https://tiptap.scrumpy.io/)

**Comment by enmust** [comment]
references sort
