### ISSUE TITLE
implement analysis functionality

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#167]
Analyses are related to samples and include data about methods, persons etc, and show numerical or other types of analytical results. Main functionality similar to sample table and detail views.

Data can be fetched:
https://rwapi.geocollections.info/analysis/22778
https://rwapi.geocollections.info/analysis_results/?analysis=22778
Write functionality to be implemented in API.
In list view the following fields will be shown:
- analysis__id
- sample__id
- sample__number
- sample__locality__locality
- sample__depth
- analysis_method__analysis_method
- date
- lab_txt
- agent__agent

Filters by: 
- analysis__id
- analysis_method__analysis_method / analysis_method__analysis_method_en
- agent__agent / lab_txt

Details view as in the old form:
![image](https://user-images.githubusercontent.com/14974887/57128847-5ed7ba00-6d9d-11e9-9039-4ad6a527c59b.png)

**Comment by enmust** [comment]
exists
