### ISSUE TITLE
site problems

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#170]
- if user opens existing site, which has no coordinates (https://edit2.geocollections.info/site/9), the systems fills them in. This should never be done automatically for existing records (but user may select a point on map to set coordinates).
- if user is on site view and selects other site from the sidebar, markers of all sites will remain on the map. The map should only show the active locality (+ GPS location if present)

**Comment by OlesjaSenkiv** [comment]
> `if user is on site view and selects other site from the sidebar, markers of all sites will remain on the map. The map should only show the active locality (+ GPS location if present)`
This case cannot be repeated.
