### ISSUE TITLE
Map component default zoom

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#178]
MapComponent2 has default zoom level set to 11. It would be more convenient to make distinction if coordinates are set or not. For maps without marker (in case of new records or existing records without coordinates set), zoom level should be 6 or 7 so that user sees entire Estonia, not small part of it. However, if latitude and longitude already exist in data, then we should zoom in to level ~15.

**Comment by ollehints** [comment]
now project and site maps should follow the same idea, currently they remain zoomed out even if coordinates are present.

**Comment by enmust** [comment]
Site should work as requested now.
Looks like project was already working as expected, if that is not the case, can you give some example links.
