### ISSUE TITLE
save as new problem

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#180]
Save as new in case of sample (https://edit2.geocollections.info/sample/145122) produced two new samples - the correct one (https://edit2.geocollections.info/sample/145202) and an extra duplicate of sample that was recently viewed (https://edit2.geocollections.info/sample/145203).
When trying to create 2 new records of sample 145179, 21! new records were created (145204-145224), with weird numbers.

**Comment by enmust** [comment]
Duplicate issue was related to #209
