### ISSUE TITLE
site adding problems

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#182]
If user creates a new site from project, and saves the site using save button, the url and route will still be https://edit2.geocollections.info/site/add, so if save is pressed again a new site will be created, but user would not see this. 
Then both save buttons will have similar effect -- they insert new records. Clear fields has no effect at all. 
Desirable behavior -- if user saves new record and stays on that record, url should change and any additional saves, should update the same record.
Another problem is that if user wants to add images or files he/she has to return to project and open the site again in order to see the add files control.

**Comment by enmust** [comment]
Should be okay now
