### ISSUE TITLE
Allow attachment type change

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#190]
Sometimes it is necessary to turn other files into photo archive records. This should be possible by clicking a button in other_file detail view (if the record appears to be image file). User should be asked to enter image_series from the selection and then image_number should be filled accordingly on save by API (need another exception in views.py) and attachment.specimen_image_attachment value should be set to 2. After save, the Photo archive record view will be shown, with additional fields, like persons etc.

**Comment by enmust** [comment]
Currently only possible to change from otherFile -> photoArchive
