### ISSUE TITLE
DOI form sections

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#194]
The DOI form general info could be separated into two collapsible sections: 
- "Mandatory fields / Kohuslikud väljad" 
  - doi - resource type general - resource type
  - title - year - publisher
- "Additional metadata / Täiendavad metaandmed".
  - ...

**Comment by enmust** [comment]
Currently there are 3 required fields, which won't let user post data without them
`requiredFields: ['publication_year', 'resource_type', 'title']`,

Should I add 'resource' and 'publisher' to that list?

**Comment by ollehints** [comment]
yes

On 29 May 2019, at 20:16, enmust <notifications@github.com<mailto:notifications@github.com>> wrote:


Currently there are 3 required fields, which won't let user post data without them
requiredFields: ['publication_year', 'resource_type', 'title'],

Should I add 'resource' and 'publisher' to that list?
