### ISSUE TITLE
html editor in project and site views

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#217]
We need a better html editor in Description field in Project and Site detailed views (and also in several other forms). Perhaps CKEditor with balloon editor (https://ckeditor.com/docs/ckeditor5/latest/examples/builds/balloon-editor.html) or tiptap with menu bubble seem to be good options (https://tiptap.scrumpy.io/). Both have vue connectors.
Also, it should be possible to blow these fields into fullscreen popup for convenient text insertion and editing.

**Comment by enmust** [comment]
Tested and both balloon/bubble editors do not work well on mobile devices. Basically phone's built in copy/select bar overrides the editor and user experience is not great.
Currently added updated version of editor options which fixed on top of input.
