### ISSUE TITLE
sample cloning problem

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#222]
sample save as new results multiple duplicates instead on just one - old problem. better to remove the button for now.

**Comment by ollehints** [comment]
however, "save as new" function is very important and saves a lot of time even if it is simple and creates a single duplicate of the current record, without subforms.

**Comment by enmust** [comment]
maybe #225 produced that error, because sample save error was because of it. I just tested save as new button and it works nicely.
