### ISSUE TITLE
Map function: Link to Estonian Geoportal (XGIS2)

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-edit#249]
Currently map has a link to Google Maps using user entered coordinates but there should also be link to XGIS2.

**Comment by ollehints** [comment]
Asked Maa-amet how to link to XGIS2, waiting answer.

**Comment by ollehints** [comment]
replay from Sulev Õitspuu, Maa-amet:

> 1)	Praegu on jah ainult LEST pöördumine. Koordinaatide teisendamise algoritmid on vabalt kättesaadavad, saab kasutada näiteks seda Maa-ameti geoportaalis olevat teenust: http://www.maaamet.ee/rr/geo-lest/ ja selle URLi põhist teisendajata (http://www.maaamet.ee/rr/geo-lest/url/) et LEST 97 XY kätte saada. 
> Ehk siis pöördumine koordinaatpaari  24.7524118419,59.0256037443  puhul (pärast koordinaatide teisendust) võiks välja näha selline: https://xgis.maaamet.ee/xgis2/page/app/geoloogia400k?punkt=6543209.9999946,543210.00000192&moot=20000 või kui soovid ka markeri juurde tooltipi lisada siis https://xgis.maaamet.ee/xgis2/page/app/geoloogia400k?punkt=6543209.9999946,543210.00000192&moot=20000&tooltip=pöördumine 

EPSG:3857 -> EPSG:3301 conversion can be easily done with proj4js (http://proj4js.org/).
