### ISSUE TITLE
Form section show/hide issue

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#251]
On data edit form (such as https://edit2.geocollections.info/reference/10515), each time when user hides or shows a form section, new query is sent to API to refresh the list in left menu. Is this necessary?
Also, on record (such as https://edit2.geocollections.info/reference/10515) reload, 3 almost identical queries are sent to API (two with paging 10, and one with paging set in earlier list view filtering).

**Comment by enmust** [comment]
Nope this is not necessary and should be fixed
