### ISSUE TITLE
Format EGF doi fields to correct doi object

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-edit#263]

**Comment by enmust** [comment]
1. What should we do with required fields: **resoruce_type**, **resource** and **publisher**
2. Also currently following fields are added to remarks in json format: **tags**, **field**, **deposit** and **emk_protocol**

Fond with an identifier 2 is hard coded to see how data is filled: https://edit2.geocollections.info/doi/add/egf/2

**Comment by ollehints** [comment]
resource_type = text
resource = "Report"
publisher = "Eesti Geoloogiateenistus"

all keywords from tags, field, deposit, emk_protocol should be inserted into tags, as comma separated values (aluspõhi, kvaliteet, kvaternaar, varu, kaardistamine, maavara, Sinimäed)

**Comment by ollehints** [comment]
authors names should be transformed into more traditional format: "Surname, F." instead of "F. Surname"
