### ISSUE TITLE
DOI save after registration

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#289]
DOI cannot be saved after registration due to date format issue:
ValidationError at /change/doi/486
["'Thu, 03 Oct 2019 17:17:36 GMT' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]

**Comment by enmust** [comment]
Did that happen when saving doi to datacite, because currently both check_metadata and check_doi show that it is saved but datacite_created and datacite_updated fields are null.
Date probably needs formatting before saving those fields in api.
