### ISSUE TITLE
change font size for user

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#305]
User should have option to change font size (probably in settings panel, saved in local settings).

**Comment by enmust** [comment]
That would be quite large update. Should that font size setting apply to everything or just certain parts of application?

**Comment by ollehints** [comment]
this is not important at the moment as user can apply browser zoom -- let's postpone this feature. But generally this is an accessibility issue: https://accessibleweb.com/question-answer/minimum-font-size/
Our user might also want to decrease zoom, to show more on single screen.

**Comment by enmust** [comment]
postponed
