### ISSUE TITLE
Implement save selection functionality for samples and specimens

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#313]
Implement functionality for saving recordsets of samples and specimens via selection and selection_series tables like in the old app.
There should be selection_series list and detail views. The latter should show related specimens and samples in non-editable tables (perhaps arranged as tabs in the form).
API calls:
https://rwapi.geocollections.info/selection_series/
https://rwapi.geocollections.info/selection/
(need to update permissions in django and update config_add)

Then specimen and sample tables should include possibility to add rows to active selection (more precisely, to selection_series). this could be done adding all filtered records to selection (limited by current paging size) or by selecting individual rows by checkboxes.

specimen and sample filters could already include selection ID and selection name parameters in filters. This works like this:
https://rwapi.geocollections.info/sample.json?selection__selection=599
https://rwapi.geocollections.info/sample.json?selection__selection__name__icontains=seth
https://rwapi.geocollections.info/specimen.json?selection__selection=640

**Comment by enmust** [comment]
> FieldError at /selection/
> Cannot resolve keyword 'specimen' into field. Choices are: database, database_id, date_added, date_changed, id, name, remarks, selection, tablename, user_added, user_changed

**Comment by ollehints** [comment]
works for specimens (for instance, filter for selection 641). 
selection details should include tables in tabs for lists of linked specimens and samples (and then other selectable tables: attachment, reference, locality, taxon).
