### ISSUE TITLE
Implement lookup type functionality

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-edit#314]
Sometimes it is needed to use different lookup types to search records (exact, startswith, endswith etc.)
Main problem is how to implement it elegantly so it would be easy to use and wouldn't take a lot of space.

**Comment by enmust** [comment]
Updated api to return all fields:
https://rwapi.geocollections.info/fields/reference
https://rwapi.geocollections.info/fields/reference?show_all=true

**Comment by ollehints** [comment]
Probably it would be better to put the filter type in front of filter field and make it shorter. Some discussion and useful UI examples at https://ux.stackexchange.com/questions/75704/what-symbol-can-be-used-to-denote-contains
We could use symbols:
- '=' for equals
- '*' for contains
- '=*' starts with
- '*=' ends with
- '>' gte
- '<' lte

We could also add 'between search' for numeric ranges that is supported by API (sign '<>').
In some rare cases 'not...' search may be useful.
