### ISSUE TITLE
Simple test interface for POST requests and file uploads needed

### ISSUE THREAD

**Issue by urtson** [geocollections/sarv-edit#315]
Starting to implement batch data import functionality. I would do it on rwapi test environment  and local database copy in .18. I can do POST requests using HTTP Request Maker or curl but adding files into request is not possible.
Perhaps we should create a simple test interface with just 2 fields: a text field for data dictionary and a file upload field. It should reside on .18, perhaps some old test version of upload/edit app can be reused if available?
Any better ideas?

**Comment by enmust** [comment]
Interface available on https://edit2.geocollections.info/test-dev
