### ISSUE TITLE
Table subforms edit issue

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#338]
Many subforms are difficult to use on small screens. For instance, it is common scenario that user wants to add sample analyses or taxa identified on mobile device (https://edit2.geocollections.info/sample/145448), but selecting data from autocomplete combos is almost impossible if the subforms contain many columns. 
The solution would be to use large (or even fullscreen) popup window for adding and editing data (sometimes useful for reading too).

**Comment by enmust** [comment]
Related to migration from bootstrap-vue to vuetify #358

**Comment by enmust** [comment]
Subforms updated
