### ISSUE TITLE
Site description by intervals

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#339]
Implement description on measured intervals for sites (and later localities - probably locality interval stratigraphy and description can come from the same table).
Locality_description model is created and present in API config but permissions need to be granted.
Site/locality descriptions may include longer texts. Also, link to images would be useful, so that describer can add images (or verbose annotation) easily while making the description.

**Comment by enmust** [comment]
test new related data

**Comment by enmust** [comment]
Link to image would need a new field

**Comment by ollehints** [comment]
django tuple index out of range error on save - maybe because year goes out as int but models expects varchar.

**Comment by ollehints** [comment]
field attachment_link.locality_description added to db, models and conf.
