### ISSUE TITLE
API to record user logins

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#364]
API should record authenticated user logins into table sarv_session. This is done by old app and data are needed for NATARC statistics. Models updated, config added for reading but permissions need to be added too. Writing would be directly by API.
Q: How to deal with long sessions and if user does not close it properly?

**Comment by enmust** [comment]
I understand that we need to log successful user logins for statistics. 
> permissions need to be added too

If you meant that users need permissions to sarv_session then I think this is not the case. If API logs user logins and writes to sarv_session then users shouldn't or even mustn't need permissions to sarv_session table.
If we would like to see log data in edit portal then admins should have permissions. 

> Q: How to deal with long sessions and if user does not close it properly?

Well if we are only logging successful logins then why would long sessions even bother us. I mean we are just writing successful logins into table for statistics. 
If we want/need to log the duration then we could edit the log data when user logs out. Also google analytics works quite well showing average user duration.

**Comment by urtson** [comment]
Sarv session start and end times are now logged. Long sessions are ended once the user is forced to log back in e.g. by session expire or browser refresh. The active flag is set to 1 for the current session and toggled on session end.
