### ISSUE TITLE
API should convert empty strings to NULL

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#384]
API should convert incoming empty strings to NULL on update requests, especially for float fields as this currently results an error, for instance: 
```
ValueError at /change/attachment/137466
could not convert string to float: 

Request Method: POST
Request URL: https://rwapi.geocollections.info/change/attachment/137466
Django Version: 2.0.5
Python Executable: /usr/bin/python3
Python Version: 3.5.3
```

**Comment by urtson** [comment]
This seems to happen when ',' is used as decimal delimiter instead of '.'  Can set up API to check the delimiter and change if needed. Same when adding new objects.

**Comment by urtson** [comment]
API can now convert comma to dot. But currently in edit2 an empty string is sent when comma is used on float field and the value will not be saved.

**Comment by ollehints** [comment]
hm, I cannot understand how and when the js app could send out numeric field containing comma. --the numeric field cannot accept comma from user input. The problem is the empty string arriving API. This should be converted to NULL before inserting into database.

**Comment by urtson** [comment]
Is the problem only with float fields or with some other type too?
The user can enter a value with comma manually, on image latitude field for example. If the field does not accept comma the value is sent out as empty string. The entered value is not saved to database but no feedback is given about this.
Currently the float values are sent as strings (at least the latitude and longitude fields on attachment) this is why 'could not convert string to float' error appears. More logical is to send them as numeric values.

**Comment by ollehints** [comment]
The last update caused error if there was no comma present so I commented this out.
I could not replicate how edit2 would sent out float as string with comma. I managed to insert comma in the field but then only empty string would be sent to API. If there is number, then it is sent as number in form data. It only becomes "" if user deletes existing value, and this causes problem with API. 
I added two lines to API code to convert all empty strings to None (NULL), regardless of field type. This may potentially have some side effects so some testing is needed. Overall it is desirable to have NULL instead of "" stored in database.

**Comment by urtson** [comment]
I have the following behaviour on edit2:
1. If coordinates are present and not changed, numeric values are sent when doing first save.
2. If I edit the coordinate, say change from 57.25 to 57.26, the number is sent as string and it will be string from now on regardless what I type on the field.
3. If I delete coordinate, empty string is sent
4. If I enter 57,26 (with comma), empty string is sent

I propose that it should be uniform, either by
1. send float always as numeric and give error on field validation in vue when wrong delimiter is used. 2. send float always as string and API does the delimiter replacement, so the user has not to bother about correct delimiter.

**Comment by ollehints** [comment]
Same behavior in my browser. But save works even if the number is sent as "image_latitude":"43.653862","image_longitude":12.696333 ...
The numeric field should only accept numeric values from user - it works this way in chrome, in FF for some reasons it is possible to input comma as well as point.
Ideally, app should always send numbers to API as numbers.

**Comment by enmust** [comment]
About the comma thing
This is default html input field behaviour. When user tries to enter wrong number format (default to type="number") then it will be emptied.

**Comment by enmust** [comment]
FYI: api returns index error which is related to float field (**Error occurs only when adding new record**).
![image](https://user-images.githubusercontent.com/14908993/72063918-6e6fb100-32e3-11ea-9a87-08f3cd515ea8.png)

data which was sent when trying to add analysis: 
![image](https://user-images.githubusercontent.com/14908993/72063989-9828d800-32e3-11ea-9f37-2560255b5017.png)

**mass** is the field which is causing that error.
