### ISSUE TITLE
Drillcore box dry/wet functionality

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#403]
Details of each drill core box cannot be managed through the drillcore forms. Thus we need to implement drillcore box views, based on old app. It should allow adding box images and selecting preferred image (need to be decided how to do that - we also need to have dry/wet functionality as for eurocore app).

**Comment by enmust** [comment]
Easiest solution could be to just add is_wet or similar field to attachment table then it would be possible to filter drillcore images either in api using is_wet=true || false or in client side.
