### ISSUE TITLE
Drillcore box image uploading

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#432]
If uploading image from box detail view, the file gets uploaded but link to drillcore_box is not created. Thus the image is not shown after refresh.

**Comment by enmust** [comment]
there is some weird issue with drillcore_box which I can't see/find out.
Api suddenly says that lookup in table 'drillcore_box' is not possible and wants the table name to be 'drillcorebox' even if config has drillcore_box.

**Comment by enmust** [comment]
This is probably related to image not uploading because currently I am using 'drillcore_box' field everywhere.

**Comment by urtson** [comment]
It is probably because drillcore_box is reverse related through AttachmentLink model and therefore it is spelled drillcorebox. Can you send the query string?

**Comment by enmust** [comment]
I mean the query is just regular id search which worked before: https://rwapi.geocollections.info/drillcore_box/5000
If you change the config from 'drillcore_box' to 'drillcorebox' then this query works: https://rwapi.geocollections.info/drillcorebox/5000

**Comment by enmust** [comment]
commit was wrongly referenced

**Comment by urtson** [comment]
Ok, that's the permissions issue. I'll find it out.

**Comment by urtson** [comment]
Now works. There was a double record in django_content_type table and permissions referenced to wrong drillcorebox content_type record.
