### ISSUE TITLE
Label printing (chrome issue)

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#433]
- While printing sample labels, some texts get underline format in print preview.
- Label size cannot be gradually adjusted in print preview like in the old app. If made large (200%) labels do not flow but will be cut.
- if collector name is longish, the date will be placed outside label. This should be avoided (better to overlap or partly hidden). 
- can we remove the section frame when printing? also, user has to hide left menu panel to avoid wide white margin.
![image](https://user-images.githubusercontent.com/14974887/73610957-ad90d980-45e5-11ea-9882-4bf99df8dcec.png)

**Comment by enmust** [comment]
Works on firefox but chrome is missing some settings. I don't know what is causing it yet.

**Comment by enmust** [comment]
Maybe its related to OS
