### ISSUE TITLE
Reference list filters problem

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#444]
Cannot filter reference list view by library title (like EPz stable isotope literature) or ID. It was working previously.

**Comment by enmust** [comment]
had to change fields from 'libraryreference' to 'libraryreference_reference'. Maybe @urtson knows why.

**Comment by urtson** [comment]
This must come from related_name argument in LibraryReference model. Was this changed recently?

**Comment by enmust** [comment]
I just looked into models: 
![image](https://user-images.githubusercontent.com/14908993/74329208-07d52b80-4d98-11ea-9694-93fabcf08e64.png)

**Comment by enmust** [comment]
I changed it back to libraryreference, because config.py has libraryreference and edit portal uses libraryreference + maybe some other places also use libraryreference field so models was easier to change

**Comment by enmust** [comment]
I tested with some requests and it seems to work.

**Comment by enmust** [comment]
okay maybe it would be logical to use libraryreference_library and libraryreference_reference, but I am leaving it like that for now:
![image](https://user-images.githubusercontent.com/14908993/74330048-a44bfd80-4d99-11ea-8ad3-a9df190ea0f2.png)
