### ISSUE TITLE
object permissions for tables with underscore

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#449]
It seems that object permission are not working for tables with underscore: drillcore_box and selection_series.

**Comment by urtson** [comment]
This is due to inconsistency in django content_type table. Model names must be without underscores. Have to find out is it safe to just rename them.

**Comment by urtson** [comment]
Fixed

**Comment by ollehints** [comment]
Now API does not work for these tables at all, regardless of object permissions e.g.,
https://rwapi.geocollections.info/selection_series/
https://rwapi.geocollections.info/selectionseries/

**Comment by urtson** [comment]
Changed how user permissions are returned on login, should now work
