### ISSUE TITLE
Remove trailing whitespace form text inserts

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#457]
This issue was up once, but has not been resolved. When users enter references they usually use copy-paste and then inserted texts often include trailing whitespace. This only becomes visible when data are concatenated into reference records and punctuation is preceded by space:
> Pap, A. M., Vetrennikov, V. V., Zhvikas, A. I., Ilkevich, G. I., Dankevich, I. V., Marfin, S. S., Maatrunchik, L. I., Petersell, V. H., Skripkina, T. S., Stasevich, A. I., 1987: Tektonika, vozrast i formacionnaâ prinadležnost' železorudnyh obrazovanij dokembriâ Belorussii i Pribaltiki . In: Garetski, R. G. (ed.). Tektonika, facii i formacii zapada Vostočno-Evropejskoj platformy. Nauka i Tehnika, Minsk, p. 15-30.

Thus we should trim text inputs before sending to the database. This could be done in app or API level.

**Comment by urtson** [comment]
API now trims spaces preceding '.'

**Comment by ollehints** [comment]
changed the code so that only leading and trailing spaces are removed. Within strings nothing can be safely removed automatically. Space before '.' only appeared when several fields were joined in output.
