### ISSUE TITLE
Cannot add taxon and subform data

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#458]
All subforms need to be checked and corrected to enable saving new taxa and individual subform data. It should be possible to add subtaxa from taxon form and jump to full view.

**Comment by ollehints** [comment]
Upon adding new taxon, after initial save, when user selects parent_taxon, hierarchy_string field should be automatically filled with parent_taxon__hierarchy_string + '-' + current record id.

**Comment by enmust** [comment]
Also attachment_link table would need a connection to taxon table

**Comment by ollehints** [comment]
taxon has different link to attachment - via taxon_image

**Comment by ollehints** [comment]
updated config_add, could now work for API, js needs to change from attachment_link to taxon_image relation. but, the current image uploading does not support filling the additional fields (https://rwapi.geocollections.info/taxon_image/606). 
workaround would be simple table, where user can select (from autocomplete) existing attachment, and add link from taxon autocomplete, and text fields title, title_en, remarks. making a custom solution would be reasonable only if many users would use this functionality.

**Comment by enmust** [comment]
Now it is possible to add both attachment record and taxon_image record from taxon view
