### ISSUE TITLE
Keyword management improvements

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#464]
In order to improve management of keywords/terms:
- Remove 'related term' since having only one related term is not sufficient
- Add field 'description' as HTML widget, followed by 'remarks'
- Add tabular subform from 'keyword_relation' table, linked via keyword field, containing two fields: keyword_relation_type__name/name_en and related_keyword__keyword. In this subform data can be added/edited.
- Add subform from keyword_relation table, linked to the current keyword using related_keyword field, containing two fields: keyword_relation_type__reverse/reverse_en and keyword__keyword. This subform should be visible below the previous one (that is not hidden to next tab), it is for information only and should provide a link to related term.
- If UI is done, copy all current related terms into new table structure (assuming they are translations).

**Comment by enmust** [comment]
Should 'related term' be also removed from the table and search?

**Comment by ollehints** [comment]
yes

**Comment by enmust** [comment]
sesose lisamisel annab niisugust errorit, aga salvestab 
![image](https://user-images.githubusercontent.com/14908993/76852934-114d2a00-6855-11ea-89ea-bdf76e9e59f6.png)

Muutmisel annab niisugust errorit ja ei salvest: 
![image](https://user-images.githubusercontent.com/14908993/76852997-2aee7180-6855-11ea-9902-f36a14378985.png)

**Comment by ollehints** [comment]
fixed in models, works now
