### ISSUE TITLE
Reference view updates

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#468]
Reference detail view needs the following updates:
- Abstract and author keywords should be on separate section / card, below other info. Label 'Keywords' should be 'Author keywords' (as it is in Estonian).
- In Other info section, the last row should include new field (first in row): **parent_reference** (showing parent_reference__reference; exists in API already), label: 'Belongs to reference' / 'Kuulub kogumikku'
- In Other info tab, update labels:
  - Original title -> Title (cyrillic) / Pealkiri (kirillitsas)
  - Book (orig.) -> Book (cyrillic) / Kogumik (kirillitsas)
  - Raamatu pealkiri (tõlgitud) -> Kogumiku tõlgitud pealkiri
  - Raamatu keel (tõlgitud) - >Kogumiku tõlke keel
  - Translated title (lang) - > Translated title language / Pealkirja tõlke keel
- Description section can be removed entirely:
  - Remarks, remarks (private), and Location fields would go into the bottom of Other info section.
  - Estonian reference, Estonian author, OpenAccess, Licence fields (in one row) should go into General info section
  - Keywords should also go into General info section as the last row - so all most heavily used fields will become easier to see / edit.

**Comment by enmust** [comment]
Should remarks, remarks (private) and location be on the same row or separate rows

**Comment by ollehints** [comment]
3 rows

**Comment by ollehints** [comment]
Few more things:
- In General info section 'Book' and 'Editor(s)' content is often longer than the fields - better to have these two fields on separate row.
- Label 'Toimetaja(d)' should be 'Editor(s)' in English
- 'Publisher' and 'Publisher place' would then go into next row. Since that row has more spare space, we can move 'Belongs to reference' into General info section, before 'Publisher' (so there will be 3 fields in that row)
- 'Belongs to reference' and 'kuulub kogumikku' translations should be switched
- 'ISBN' and 'ISSN' can be moved to the last row in the section, after 'Location' (so that there will be 3 fields in that row)
