### ISSUE TITLE
API default view

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#470]
Could we make default API response return JSON instead of HTML? For the object list views like https://api.geocollections.info/reference and https://api.geocollections.info/solr/reference the load and parse times would hugely benefit from this. Developer has then option to specify ?format=api if nice view is necessary.

**Comment by urtson** [comment]
Rest framework allows to change the order of default renderer classes in settings.py but it seems to have effect only when BrowsableAPIRenderer is removed from the list and then there would be no api format option. We could do that, in which cases is api format needed anyway?

It seems that API view is also json: Content-Type: application/json, just parsed to html to display in browser.
If you omit format=json in edit2 queries for example, isn't the response still json?

**Comment by enmust** [comment]
>  is api format needed anyway?

I think from a dev's perspective I wouldn't lose that functionality because it makes responses readable which is essential for developing, debugging etc.

> If you omit format=json in edit2 queries for example, isn't the response still json?

Yep, it is still json, basically it doesn't matter if you put format=json into query or not because you get the same result. It's just that for larger requests format=api starts to get slow.

**Comment by enmust** [comment]
Default is now json

**Comment by enmust** [comment]
Had to change default render ordering according to django docs https://www.django-rest-framework.org/api-guide/renderers/

I tested and works, while sending requests it default to json format but when viewing from browser the default is api format
