### ISSUE TITLE
keyword new field

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#471]
In keyword detail form:
- Label for 'is_primary' should be 'Base term (to translate etc)' / 'Baastermin (mida tõlkida)'
- Add checkbox field 'is_preferred' (after is_primary) with label 'Preferred (in selected language)' / 'Eelistatud (valitud keeles)'

In table view:
- have both is_primary and is_preferred fields displayed as in case of loan table 'returned' icon. labels: 'Base term'/'Baastermin', 'Preferred'/'Eelistatud'.

**Comment by ollehints** [comment]
one more addition to guide users - if a term is marked as base term, then it should not be translation or synonym or etc of another term. Instead, other terms may be translations or synonyms of the base term. Thus it is better to not allow users entering related terms for base terms. So we need to hide the first related terms subform if 'is_primary' is checked.

**Comment by enmust** [comment]
So if is_primary=true then user should not be able add or edit 'keyword_relation' table moreover if keyword has is_primary=true then this record shouldn't even have any keyword relations? For example keyword 513 shouldn't have that relation?

What about those records that already have keyword_relations but are changed to base terms? Should it be done like that when user tries to set is_primary to true then it sends empty keyword_relation through related_data to clear existing relations?

**Comment by ollehints** [comment]
Problems with existing records cannot be fully avoided -- old data needs to be corrected, for instance, keyword/513 should not be base term. Maybe just remove add and edit buttons if the active record is base term. then if user unchecks the 'base term', he/she will be able to add/edit related terms. This would be mild forcing.

**Comment by ollehints** [comment]
* in table view, is_preferred is always indicated by red minus 
* in detail view, if user checks base term, is_preferred should be automatically checked.
* by default base term should not be checked (but it will be on first save even if not checked by user), but the preferred should be checked (currently it will become checked after save even if not indicated by user).

**Comment by enmust** [comment]
Default data is sent like that (no user interaction yet):
![image](https://user-images.githubusercontent.com/14908993/78031773-a92a3800-736c-11ea-8b4f-3f2bb772d2fd.png)

Keyword model has following settings:
![image](https://user-images.githubusercontent.com/14908993/78031646-7ed87a80-736c-11ea-929d-9af9f19f1450.png)
 
That's why the issues, but I changed it in the app so that the 'is_primary' is false by default and 'is_preferred' is true.
