### ISSUE TITLE
Editing one-to-one related data

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#476]
New table site_groundwater is linked to site using Django's OneToOneField field relationship. The table contains hydrogeology data and can be taken as extension of the regular site table. What would be the best way to add/edit these 'extension table' fields in API? 
In UI the easiest would be an accordion section under the site detail view with 'extension table' fields.

**Comment by enmust** [comment]
If needed, similarly to every other view we could still do the same add, edit and table views for site_groundwater. Just 'site' object has to be mandatory field. 

I understand that the main use would be to add/edit it from the site view. I think I would solve it similarly to related_data. 

Hydrogeology data would appear in a new card, for example under 'Description | Remarks'

From the top of my head some solutions:
- To view data I would use text fields:
    - **changeable** fields
        - Then to add and edit you could just directly change text fields but the save would work with a button which is on the same card or maybe get it to work with main save button. (might confuse user?)
        - Use toggle button to change textfield's read only state - then save would work when user presses toggle button to disable editing. 
    - **read only** fields
        - Then  add and edit would be through modal similarly to related_data.

**Comment by urtson** [comment]
From API side it could be the ordinary way. While adding, site ID must be specified, while changing site ID is optional.

**Comment by ollehints** [comment]
Easiest would then be to include a section with regular fields and a separate save button. Section title: Groundwater extension / Põhjavee laiendusmoodul. The section would be shown only to those who have permission to site_groundwater table. The fields to show/edit would be:
- type_txt, aquifer_system, aquifer / labels: Type, Aquifer, Aquifer system
- well_depth, filter_type / Well depth, Filter type
- filter_top, filter_bottom, filter_top_z, filter_bottom_z / Filter top (b.g.s), Filter bottom (b.g.s), Filter top (a.s.l), Filter bottom (a.s.l)
- url_veka | remarks / VEKA link, Remarks

**Comment by ollehints** [comment]
Cannot update existing groundwater extension data, error: "can't change field id".

**Comment by ollehints** [comment]
Separate hydrogeology views are probably not needed as of now - only in few cases the list view could be useful (for searching or sorting by hydrogeology specific fields that we do not want to include in the main site search/list view), but then, too, it should direct the user to site detail view.
