### ISSUE TITLE
Sample form updates

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#477]
Samples should preferably not be related to lat long coordinates directly - better way is through the site abject which allows to specify precision etc. Thus, we can replace latitude and longitude fields in the form with site field (which is currently too far away from other location fields anyway).
In simple view, site could replace storage2 field which is not useful in simple view.

Additional remark: sample series translates into Prooviseeria (not Proovi valikud) in left menu. Also, views that are not heavily used, like 'Add sample series', might be accessed via table view and 'add new' button - since the menu is quite crowded already.

**Comment by enmust** [comment]
Which 'add' views should be removed from the left menu?

**Comment by ollehints** [comment]
If user switches from full sample view to simple view, site is not shown in the form field, and if user switches back to full view, site field is empty there too.
