### ISSUE TITLE
New fields for site views

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#481]
It appears necessary to distinguish different site types. New field **site_type** added for this, linked to the list of predefined values in the site_type table. 
In site list view, site_type__value / site_type__value_en could be shown between number and project fields.

In detail view, the new autocomplete field should fit into General info tab. We also need to show number and date_free fields, need 3 lines for that:
- name, name_en, number, type
- date start, date end, date_free
- area, project

Maybe in the future we need a simplified version for mobile screens at fieldwork.

In Groundwater extension two new fields introduced, the last two lines in the form would be:
- kataster_id (Katastrinumber), keskkonnaregister_id (Keskkonnaregistri ID)', veka_url (VEKA link, could be link to outer url to be opened in new window)
- remarks

**Comment by ollehints** [comment]
list from API: https://rwapi.geocollections.info/site_type/

**Comment by ollehints** [comment]
- Cannot save groundwater data:
ValueError at /add/site_groundwater/
Cannot assign "'8693'": "SiteGroundwater.site" must be a "Site" instance.
Probably need to send site as integer rather than text, or edit config for related data?
- Keskkonnaregister ID should be text field, not number.

**Comment by ollehints** [comment]
still problem in saving https://edit2.geocollections.info/site/8693
Exception Type: ValueError at /change/site_groundwater/153
Exception Value: Cannot assign "8693": "SiteGroundwater.site" must be a "Site" instance.
Request information:
USER: olle

GET: No GET data

POST:
data = '{"site":8693,"aquifer_system":"Kambriumi-Vendi","aquifer":"V2vr-kt","well_depth":125,"type_txt":null,"filter_type":"perfofilter","filter_top":107.2,"filter_bottom":125,"kataster_id":null,"keskkonnaregister_id":"PRK0002260","url_veka":"http://otsi.eelis.ee/PRK0002260","remarks":null}'

**Comment by urtson** [comment]
The problem was in API as OneToOneField was a new field type for it. Try again if works

**Comment by ollehints** [comment]
now the error is different:
TypeError at /change/site_groundwater/153
int() argument must be a string, a bytes-like object or a number, not 'dict'

**Comment by enmust** [comment]
Now live version also works

**Comment by enmust** [comment]
There are some problems with number fields, currently working on it

**Comment by enmust** [comment]
Should work now
