### ISSUE TITLE
Attachment object permissions

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#503]
Row-level permissions activated for attachments. Thus the current author/user_added filters can be removed. However, speed needs to be tested more thoroughly - on some occasions it seems to be very slow.
Attachment detail view should have permissions section.

**Comment by ollehints** [comment]
It is common to get response times tens of sec: https://rwapi.geocollections.info/attachment.json?id__gte=1000
Maybe upgrade to a more recent Guardian has effect (2.3.0 vs 1.4.9), otherwise we need to seek for a snappier solution than Guardian.

**Comment by enmust** [comment]
Closing this because search query is updated and perms sections added. Speed issue is already mentioned in #429
