### ISSUE TITLE
Stratigraphy form fields update (size, order etc.)

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#504]
Two new fields added: maaamet_kood and index_old
Table view filters should include: 
- 'Indexes' that would search from index_main, index_additional and index_old fields.
- 'author' search from author
- can we do hierarchical search based on parent_id? so that user can get all units belonging to, say, 'Ordovician'

To do: revise the order and size of fields, and label names in detail view

**Comment by enmust** [comment]
Only this is left:

> To do: revise the order and size of fields, and label names in detail view

**Comment by enmust** [comment]
Opened new issue for the field revision
