### ISSUE TITLE
Select photo site from map problem

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#523]
It is convenient that the location data from previous record are remembered if many images are from the same site. However, if the location changes it is time-consuming to drag the marker. If user manually deletes the coordinates, then there is no marker on the map and user cannot set new location by clicking on the map (as the app expects dragging marker).
A solution would be to add a button 'Reset location data' that will empty coordinate fields and allow setting new location by clicking on the map.
It would also be helpful, if user selects photo locality, and the locality has coordinates, then the coordinates would be used for default (if the photo contain GPS data then that would be of priority).

**Comment by ollehints** [comment]
Related issue: 'Remove defaults' should clear the current (new) record - at the moment user does not see a change after pushing this button (or has to reload the page manually).

**Comment by enmust** [comment]
Coordinates from locality search update: coordinates are updated only if latitude and longitude fields are empty (not overwriting existing coordinates).
