### ISSUE TITLE
sample image upload issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#527]
Sometimes user would like to add several images for a sample, but this has issues:
The first image gets uploaded and relation saved, but if user adds second image, error appears: '1048: column filename cannot be null'. If user reloads page after adding first image, then another one can be added.
If user saves sample record without reloading page, then image links will be rewritten and the newly added images un-linked from the sample. Check history of https://edit2.geocollections.info/sample/180433

**Comment by enmust** [comment]
New files can't be added one by one (index error)

relations dropped after adding new files and saving record (have to update files)
