### ISSUE TITLE
location table upload error

### ISSUE THREAD

**Issue by enmust** [geocollections/sarv-edit#535]
API throws key error:
![image](https://user-images.githubusercontent.com/14908993/91861617-b62db900-ec75-11ea-8ec6-91da5cb21c55.png)
and suggests choices related to 'attachment_link' table

**Comment by enmust** [comment]
Fixed (problem was in write_views), image related

![image](https://user-images.githubusercontent.com/14908993/93105130-5d1f4580-f6b7-11ea-8b53-2afdf6eacaeb.png)

**Comment by ollehints** [comment]
while trying to add existing image (s347-8.jpg) to https://edit2.geocollections.info/location/13798 the update fails with: 
TypeError at /change/location/13798
'location' is an invalid keyword argument for this function
Works when uploading a new file though.

**Comment by enmust** [comment]
Fixed now.

Note to self: write_views.py lines: 564, 607, 620
