### ISSUE TITLE
Implement analysis method views

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#536]
Implement search/list and detail views for analysis_method. 
Search fields would be id, analysis_method, parent_method__analysis_method and remarks.

**Comment by enmust** [comment]
Related parameter not showing up in form but data is there
![image](https://user-images.githubusercontent.com/14908993/92257179-7701a100-eedd-11ea-9f1a-2c05fdc50793.png)

Fix: You have to push it to list in fillAutocompleteFields method, pic related
![image](https://user-images.githubusercontent.com/14908993/92257489-f8593380-eedd-11ea-980e-9fe9f534902a.png)

Same applies to #537
