### ISSUE TITLE
Show storage images in list view

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#539]
Show storage (location) images in list view, similarly to specimen table/image view.
Thumbnail should include eye icon - click on which would open large image file in separate window (like in case of specimen).
Regular click on image should open the storage for editing.
If storage has no image, empty thumbnail should be shown.
If storage has more than one image, the latest should be displayed.

**Comment by enmust** [comment]
Should get results from 'attachment_link' table directly

**Comment by enmust** [comment]
That probably means we need to make 'uuid_filename' dynamic like 'idField' in ImageViewWrapper.vue
