### ISSUE TITLE
Show storage labels

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#540]
Add storage label view for printing, based on the design of the old app.
It should be foreseen, that different storage labels may be needed (separate labels for boxes, drawers, institutions etc).
QR code should be present and direct to storage edit view: https://edit.geocollections.info/location/11373
![image](https://user-images.githubusercontent.com/14974887/91875028-a026f500-ec83-11ea-907a-4dbdc3e5a8d9.png)

**Comment by enmust** [comment]
![image](https://user-images.githubusercontent.com/14908993/92450234-d6a0ca80-f1c3-11ea-9da3-54ec2380d61b.png)

![image](https://user-images.githubusercontent.com/14908993/92450646-5d55a780-f1c4-11ea-9cbd-1d57444d1944.png)

**Comment by enmust** [comment]
append small padding and close
