### ISSUE TITLE
Drillcore box alternative list views 

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#541]
Drillcore box filter/list view (https://edit2.geocollections.info/drillcore_box) should have separate view with box images, one for each box (if no image, placeholder should be shown), similar to file list view where images are shown within table. When clicking on box image, large image should be shown in separate popup window (that will remain open so that two or more box images can be compared).
A different view is needed for printing box images into pdf (two landscape images per portrait A4 sheet): 
￼ ￼
![PNG image](https://user-images.githubusercontent.com/14974887/91879338-a8356380-ec88-11ea-8c78-695d7bfded77.png)

**Comment by enmust** [comment]
Tested and images still not appearing (both firefox and chrome)
