### ISSUE TITLE
Reference pdf upload duplicate icon issue

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#547]
If user uploads a pdf on reference form (https://edit2.geocollections.info/reference/24116), then two pdf icons are shown after upload. After reload, everything is normal.
![image](https://user-images.githubusercontent.com/14974887/92304941-5859e380-ef8b-11ea-8a8a-567e38dc9e65.png)

**Comment by enmust** [comment]
related to recent issue #546
