### ISSUE TITLE
DOI module enhancements

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#555]
- For new records Publisher field should come from a controlled list of values. These are present in doi_publisher table (https://rwapi.geocollections.info/doi_publisher - permissions still need to be adjusted), the ID 1 should be the default value, but user should be shown a list of options. Old records should not be linked to publisher at present.
- We need to overcome the problem with two fields for authors. Can we make the author field non-editable and filled/updated automatically if the related persons list of creators gets updated? The subform should then become obligatory.
- Why some records do not show metadata and doi register / update buttons? https://edit2.geocollections.info/doi/16
- version should be 1.0 by default.
- can we add tooltips to some fields? For instance, formats field should advise the user: "Siia lahtrisse sisesta lisatavate failide  laiend, nt pdf, xlsx või csv; mitme faili puhul eralda need kooloniga".

**Comment by enmust** [comment]
> Why some records do not show metadata and doi register / update buttons? https://edit2.geocollections.info/doi/16
Not showing buttons because of #516

**Comment by enmust** [comment]
To see register and updated buttons files have to be added #516 but sometimes users do not see files because they do not have permissions.
