### ISSUE TITLE
Extend app coverage?

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#71]
The upload app works pretty well. The same software components and UI design could be used to extend the functionality to other data objects and functions. Notably there is a need to more easily manage references and samples (including on mobile devices). This would allow widening the user base. The question is how to do this -- rename the app and extend functionality, create a clone and start new small app(s), or something else?

**Comment by enmust** [comment]
I think it would make sense to just extend functionality like adding references, samples and so on. 

It seems pointless to make lots of different apps basically with the same functionality and design.

**Comment by ollehints** [comment]
decided.
