### ISSUE TITLE
Managing references

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#81]
The app should allow managing references, reference collections (table library) and journals.
The current reference window is shown below, new one could be arranged similarly.
References are common to all users and should be editable to everybody who has reference_edit permission in django permissions. 
Development of functionality:
- add and edit references
- add related localities and keywords (using similar UI solution as file view)
- add linked file by dragging pdf 
- add journals
- add and edit reference collections (library), which are user based (link by author_id and user_added like in case of files).
- implement convenient way to adding and managing references under library
- allow adding active reference to my library in reference add/edit view 

![image](https://user-images.githubusercontent.com/14974887/48299717-9a25ba00-e4d9-11e8-97a4-9a41f013eb5c.png)

**Comment by enmust** [comment]
Should references, journals and libraries be in the same view or should I separate them like in file adding view (photo archive, specimen image etc.)

**Comment by enmust** [comment]
Also it would be a lot easier if I had some kind of template like there was for attachments, for example which fields are needed, default values etc.

**Comment by ollehints** [comment]
will work on longer description, but:
- the required fields in reference add/edit form are reference, author, year, title.
- default values only in two fields: language = english, type = journal article.
- no values should be remembered from previous insert.
- journal form should be popup, similar to imageset form.
- reference collection should be separate form like reference, with list and detail view/insert/edit views. will provide layout scheme later as separate issue.

**Comment by enmust** [comment]
@urtson How should I send localities and files, currently I'm sending them under related_data like that
![image](https://user-images.githubusercontent.com/14908993/50726169-db210000-1111-11e9-8ea4-4b3c24806bd1.png)

**Comment by urtson** [comment]
Yes, send as related data as above. This should now work for every table specified in config_add. 
Note that only 'id' field is needed for each object as filtering is done on the form.
Intermediate tables are now also specified in config, so by attachment upload the 'attach_link__' prefix can/should now be omitted.

**Comment by ollehints** [comment]
mostly done, small remaining things filed as separate issues
