### ISSUE TITLE
url routing and duplication in templates

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#92]
Urls for all views should be more conventional, like:

- https://edit.geocollections.info/reference - show table view with filters
- https://edit.geocollections.info/reference/123 - one reference, for viewing and editing.
- https://edit.geocollections.info/reference/add - empty reference form for saving new record, the template should be the same as in edit mode.

instead of:
- https://edit.geocollections.info/#/add/reference/reference

**Comment by enmust** [comment]
Which way is preferred https://edit.geocollections.info/attachment/add/photo_archive or https://edit.geocollections.info/attachment/photo_archive/add

**Comment by ollehints** [comment]
the question is -- will there be anything at https://edit.geocollections.info/attachment/photo_archive?
currently all attachments are shown together and single record, too, does not have (and does not need) the photo_archive part. thus the first option is more logical one to use.
