### ISSUE TITLE
Library views

### ISSUE THREAD

**Issue by ollehints** [geocollections/sarv-edit#95]
API should now support library management. 
Outline of two main views drafted below.
Once a library is defined it will be mostly used via reference views (reference table view should allow filtering by users own libraries, linking to library should be possible from reference view etc -- these will be added as separate issues once the main functionality is in place).

![library_views](https://user-images.githubusercontent.com/14974887/52178859-d10b2380-27db-11e9-8383-a66e50f79a97.PNG)

**Comment by ollehints** [comment]
Perhaps it would be easiest to manage library publications using subform like in case of sample for instance: https://edit2.geocollections.info/sample/145090
Subform should then show values from library_reference table: reference__reference in combo, keywords and remarks.
Then the regular reference list view would have search filter to display nice reference list: library (searching for using library__id, library__title, library__title_en), with paging 25 or so.

**Comment by enmust** [comment]
Do you mean these 3 search fields should be in .../reference and only seen when user uses list view?

**Comment by ollehints** [comment]
there would be just one additional search field in /reference but it would filter by library id, title and title_en. no change in list/table views needed.

**Comment by ollehints** [comment]
Library model was updated to include many-to-many relation with agent. 
This would replace the functionality of both author_id and author_txt fields in the future. 
Also, current user libraries should be asked from the library_agent table like: https://rwapi.geocollections.info/library_agent/?agent=7
So that all "members of the library" may manage the library record and add/update references linked to it. Agent selection could be the same widget as used in project detail view to manage project members.
https://edit2.geocollections.info/project/3
